services:
  altcha-server:
    build: .
    container_name: altcha-service
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env
    restart: always
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./database:/app/database
      - ./web:/app/web
    networks:
      - altcha-net

  redis:
    image: redis:alpine
    container_name: redis-service
    command: >
      --maxmemory 256mb  --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 2s
      retries: 5
    restart: always
    networks:
      - altcha-net

networks:
  altcha-net:
    name: altcha-net
    driver: bridge
